services:

  app:
    image: eclipse-temurin:17-jdk-alpine
    container_name: app-vuelos
    volumes:
      - ./target/reserva-0.0.1-SNAPSHOT.jar
    working_dir: /reserva
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=reserva-db;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: reservaVuelos2019
    networks:
      - app-vuelos

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: vuelos-db
    hostname: sql1
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: reservaVuelos2019
    ports:
      - "1433:1433"
    networks:
      - app-vuelos

networks:
  app-vuelos:
    driver: bridge